#ddev-generated
webimage_extra_packages: [build-essential]
# static-php-cli requires at least php 8.4 to build, but the resultant php binary will be as set in
#
php_version: 8.4
hooks:
  post-start:
    - exec: "sudo ln -sf /usr/local/src/static-php-cli/buildroot/bin/php /usr/bin/php"
    - exec: sudo ln -sf /usr/local/src/static-php-cli/buildroot/bin/php-fpm /usr/sbin/php-fpm
    - exec: sudo ln -sf /etc/php/${STATIC_PHP_VERSION%.*}/cli/php.ini /etc/php.ini
    - exec: sudo ln -sf /etc/php/${STATIC_PHP_VERSION%.*}/fpm/php-fpm.conf /etc/php-fpm.conf
    - exec: "killall -HUP supervisord && rm -f /tmp/healthy && while true; do sleep 1; if /healthcheck.sh >/dev/null; then break; fi; done"

